Text_Automation ="//h1/span[text()='Automation']"
Header_Contact_us="//h2[text()='Contact us:']"
Textbox_FirstName_Automation_Page ="//label[text()='First Name']/following-sibling::input"
Textbox_LastName_Automation_Page ="//label[text()='Last Name']/following-sibling::input"
Textbox_Email_Automation_Page ="//label[text()='Email']/following-sibling::input"
Textbox_Phone_Automation_Page ="//label[text()='Phone']/following-sibling::input"
Textbox_Company_Automation_Page ="//label[text()='Company']/following-sibling::input"
Dropdown_Country_Automation_Page="//label[text()='Country']/following-sibling::div/select"
Textarea_Message_Automation_Page="//label[text()='Message']/following-sibling::textarea"
Checkbox_I_agree_Automation_Page="//input[@type='checkbox']/following-sibling::label[text()='I agree']"
Checkbox_I_am_not_robot_Automation_Page="id=recaptcha-anchor-label"
Button_Submit_Automation_Page="//button[@name='submit']"
Iframe_recaptcha="//iframe[@title='reCAPTCHA']"
